# Intro

## **Before starting this library, we need to know the basics of Python which includes below:
Matrices, lists, tuples, for loops, classes, dictionaries 

### Python version

In [1]:
import numpy as np
print(np.__version__)

1.23.4


### np.array()

In [2]:
print(np.array([[1,2], [4,5]]))

[[1 2]
 [4 5]]


In [3]:
w1= np.array([[1,2], [3,4]], dtype=complex)
w2= np.array([(1,2), (3,4)], dtype=complex)
w3= np.array(([1,2], [3,4]), dtype=complex)
w4= np.array(((1,2), (3,4)), dtype=complex)
print("w1= ", w1,"\nw2= ",w2,"\nw3= ", w3, "\nw4= ",w4)

w1=  [[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]] 
w2=  [[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]] 
w3=  [[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]] 
w4=  [[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


### _.ndim, _.shape, _.size, _.dtype.name, _.itemsize

In [4]:
c=np.array([[1,2], [4,5]])
print(c)
print(type(c))
print(c.ndim, c.shape, c.size, c.dtype.name, c.itemsize)

[[1 2]
 [4 5]]
<class 'numpy.ndarray'>
2 (2, 2) 4 int32 4


### np.arange (start, stop, step)

In [5]:
a=np.arange(20)
print("a= \n", a)

print(a[-8:17:1])

print(a[10:])

a= 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[12 13 14 15 16]
[10 11 12 13 14 15 16 17 18 19]


In [6]:
a= np.arange(15)

print(a)
print(type(a))
print(a.ndim, a.shape, a.size, a.dtype.name, a.itemsize)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>
1 (15,) 15 int32 4


In [7]:
d= np.arange(10,30,2)
print(d)

s=np.arange(0,2,0.3)
print(s)

[10 12 14 16 18 20 22 24 26 28]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


### np.linspace(start, stop, num , endpoint)  , np.logspace(start , stop , num , endpoint)

In [8]:
l=np.linspace(10,30,6)   #6 is amount
print(l)

a= np.arange(10,30,6)  #6 is step
print(a)

[10. 14. 18. 22. 26. 30.]
[10 16 22 28]


In [9]:
import numpy as np

a= np.linspace(2.0,3.0,num=12)
print(a)
print("-----------------------")

s=np.linspace(2.0,3.0,num=12,endpoint=False)  #without 3.0
print(s)
print("-----------------------")

w=np.logspace(2.0,3.0,num=4)             #logarithm of 4 numbers between 2 and 3
print(w)
print("-----------------------")

q=np.logspace(2.0,10.0,num=4,endpoint=False)
print(q)

[2.         2.09090909 2.18181818 2.27272727 2.36363636 2.45454545
 2.54545455 2.63636364 2.72727273 2.81818182 2.90909091 3.        ]
-----------------------
[2.         2.08333333 2.16666667 2.25       2.33333333 2.41666667
 2.5        2.58333333 2.66666667 2.75       2.83333333 2.91666667]
-----------------------
[ 100.          215.443469    464.15888336 1000.        ]
-----------------------
[1.e+02 1.e+04 1.e+06 1.e+08]


### np.reshape() 

In [10]:
b= np.arange(9).reshape(3,3)

print(b)
print(b.ndim, b.shape, b.size, b.dtype.name, b.itemsize)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
2 (3, 3) 9 int32 4


In [11]:
d= np.arange(24).reshape(2,3,4)
print("d is: ",d)
print(d.ndim, d.shape, d.size, d.dtype.name, d.itemsize)

d is:  [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3 (2, 3, 4) 24 int32 4


In [12]:
s= np.arange(10000)
print("s is: ",s ,"index98 is ",s[98])
print("---------------------------------------")

print(np.arange(10000).reshape(5,20,100))

s is:  [   0    1    2 ... 9997 9998 9999] index98 is  98
---------------------------------------
[[[   0    1    2 ...   97   98   99]
  [ 100  101  102 ...  197  198  199]
  [ 200  201  202 ...  297  298  299]
  ...
  [1700 1701 1702 ... 1797 1798 1799]
  [1800 1801 1802 ... 1897 1898 1899]
  [1900 1901 1902 ... 1997 1998 1999]]

 [[2000 2001 2002 ... 2097 2098 2099]
  [2100 2101 2102 ... 2197 2198 2199]
  [2200 2201 2202 ... 2297 2298 2299]
  ...
  [3700 3701 3702 ... 3797 3798 3799]
  [3800 3801 3802 ... 3897 3898 3899]
  [3900 3901 3902 ... 3997 3998 3999]]

 [[4000 4001 4002 ... 4097 4098 4099]
  [4100 4101 4102 ... 4197 4198 4199]
  [4200 4201 4202 ... 4297 4298 4299]
  ...
  [5700 5701 5702 ... 5797 5798 5799]
  [5800 5801 5802 ... 5897 5898 5899]
  [5900 5901 5902 ... 5997 5998 5999]]

 [[6000 6001 6002 ... 6097 6098 6099]
  [6100 6101 6102 ... 6197 6198 6199]
  [6200 6201 6202 ... 6297 6298 6299]
  ...
  [7700 7701 7702 ... 7797 7798 7799]
  [7800 7801 7802 ... 7897 7898 7899

### np.where (condition, where true X, where false Y])

In [13]:
c= np.array([(1.5,2,3), (4,5,6)])
print("c is: ", c)
print('--------------')

print(np.where(c>5, c,0))

c is:  [[1.5 2.  3. ]
 [4.  5.  6. ]]
--------------
[[0. 0. 0.]
 [0. 0. 6.]]


### np.zeros(shape) , np.ones(shape) , np.full(shape , fill_value , dtype)

In [14]:
a=np.zeros([2,5])
print(a)
print('----------------')

b= np.ones([2,3,5], dtype=np.int16)
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
----------------
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [15]:
a= np.array([[1,2,4], [5,8,7]], dtype ='float')
print("a= ", a)

b= np.array((1,3,2))
print("b= ", b)

c= np.zeros((3,4))
print("c= ", c)

d= np.full((3,3), 6, dtype= 'complex')
print("d= ", d)

a=  [[1. 2. 4.]
 [5. 8. 7.]]
b=  [1 3 2]
c=  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
d=  [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


### np.random.random(shape) 

In [16]:
e= np.random.random((4,4))  #first random called the module    #second random create a random array
print("e= ", e)

f= np.arange(0,30,5)
print("f= ", f)

g= np.linspace(0,5,10)
print("g= ", g)

e=  [[0.5317554  0.25069802 0.24061427 0.54692697]
 [0.18797495 0.17860289 0.17714549 0.68302875]
 [0.01193214 0.90180542 0.42602459 0.08418794]
 [0.03049785 0.43163696 0.95875963 0.56288459]]
f=  [ 0  5 10 15 20 25]
g=  [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


###  _.flatten()   , np.ravel()

In [17]:
arr= np.array([[1,2,3,4],
                [5,2,4,2],
                [1,2,0,1]])
newarr= arr.reshape(2,2,3)
print("arr= ", arr)
print("newarr= ", newarr)

arr1= np.array([[1,2,3], [4,5,6], [8,9,10]])
flarr= arr.flatten()
print("flarr= ", flarr)

arr=  [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
newarr=  [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]
flarr=  [1 2 3 4 5 2 4 2 1 2 0 1]


In [18]:
import numpy as np
a= np.array([[1,2,3],
            [4,5,6],
            [7,8,9],
            [10,11,12]])

print("a= \n", a)

print("shape=",a.shape)

print("ravel=",np.ravel(a))

print(a.reshape(6,2))

a= 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
shape= (4, 3)
ravel= [ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


## Mathematic in Numpy

### [+ , - , * , / , **] , pi , np.sin() ... , Transpose -> .T

In [19]:
a= np.array([1,2,5,3])

print("a+1= ",a+1)
print("a-3= ",a-3)
print("a*10= ",a*10)
print("a**2= ",a**2)

a *= 2
print("2a= ",a)

a+1=  [2 3 6 4]
a-3=  [-2 -1  2  0]
a*10=  [10 20 50 30]
a**2=  [ 1  4 25  9]
2a=  [ 2  4 10  6]


In [20]:
from numpy import pi

x= np.linspace(0, 2*pi, 4)
print("x= ",x)

f= np.sin(x)
print("f= ",f)

x=  [0.         2.0943951  4.1887902  6.28318531]
f=  [ 0.00000000e+00  8.66025404e-01 -8.66025404e-01 -2.44929360e-16]


In [21]:
b= np.array([[1,2,3], [3,4,5], [9,6,0]])
print("b= ", b)
print("b Transpose= ", b.T)

b=  [[1 2 3]
 [3 4 5]
 [9 6 0]]
b Transpose=  [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [22]:
import numpy as np

a= np.arange(12)**2
print(a)

i=np.array([1,2,3,8,5])
print(a[i])
print("-----------------")

j=np.array([[-1,-3,-5],[4,2,1]])
print(a[j])

[  0   1   4   9  16  25  36  49  64  81 100 121]
[ 1  4  9 64 25]
-----------------
[[121  81  49]
 [ 16   4   1]]


### _.max(axis= ) , _.min(axis= ) , _.sum( ) , _.cumsum(axis= )
axis=1 ---> Rowweise ---------- axis=0 ---> Columnweise

In [23]:
arr= np.array([[1,5,6],
               [4,7,2],
               [3,1,9]])
print("arrMAX= ", arr.max())
print("arrRowMAX= ", arr.max(axis=1))
print("arrColumnMIN= ", arr.min(axis=0))
print("arrSum= ", arr.sum())
print("arrRowSum= \n", arr.cumsum(axis=1))
print("arrColumnSum= \n", arr.cumsum(axis=0))

arrMAX=  9
arrRowMAX=  [6 7 9]
arrColumnMIN=  [1 1 2]
arrSum=  38
arrRowSum= 
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]
arrColumnSum= 
 [[ 1  5  6]
 [ 5 12  8]
 [ 8 13 17]]


### _.dot(_)  --->  Matrix Multiplication

In [24]:
a= np.array([[1,2],
             [3,4]])
b= np.array([[4,4],
             [5,6]])

print("Sum=\n", a+b)
print("Product=\n", a*b)
print("Matrix Multiplication=\n", a.dot(b))

Sum=
 [[ 5  6]
 [ 8 10]]
Product=
 [[ 4  8]
 [15 24]]
Matrix Multiplication=
 [[14 16]
 [32 36]]


### np.sqrt() 

In [25]:
a= np.array([0, np.pi/2, np.pi])
print("Sine values of array elements: ", np.cos(a))
print("Square root of array elements: ", np.sqrt(a))

Sine values of array elements:  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Square root of array elements:  [0.         1.25331414 1.77245385]


### np.sort(array, axis= , kind= , order= )

In [26]:
b= np.array([0,10,8,3,15])
print("Sorted copy of array elements: ", np.sort(b))

Sorted copy of array elements:  [ 0  3  8 10 15]


In [27]:
a= np.array= ([[1,4,2],
               [3,4,6],
               [0,-1,5]])
print("sorted array: \n", np.sort(a, axis= None))

print("Row sorted array: \n", np.sort(a, axis= 1))

print("Coulmn merged sort: \n", np.sort(a, axis=0, kind='mergesort'))

sorted array: 
 [-1  0  1  2  3  4  4  5  6]
Row sorted array: 
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Coulmn merged sort: 
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


### np.asarray([list] , dtype= )

In [28]:
list1= [1,2,3,4,5,6]
list2= [10,9,8,7,6,5]

a1= np.asarray(list1)
a2= np.asarray(list2)

print(a1*a2)

[10 18 24 28 30 30]


In [29]:
a=np.arange(10,1,-2)      #a is a numpy array
print("a= \n",a)
print(type(a))
b= a[np.asarray([3,1,2])]    #b is a numpy array from a list of a
print("b= \n", b)
print(type(b))

a= 
 [10  8  6  4  2]
<class 'numpy.ndarray'>
b= 
 [4 8 6]
<class 'numpy.ndarray'>


In [30]:
dtypes= [('name', 'S10'), ('grad_year', int), ('cgpa', float)]      #'S10' means the type is string 

values= [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7),
         ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]

arr= np.asarray(values, dtype = dtypes)                  ######?????????????

print("array sorted by names: \n", np.sort(arr, order='name'))
print("array sorted by graduation year and then cgpa: \n", np.sort(arr, order=['grad_year', 'cgpa']))

array sorted by names: 
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
array sorted by graduation year and then cgpa: 
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


### np.fromfunction(funktion, shape, dtype, like)

In [31]:
# from gettext import npgettext


import numpy as np

def f(x,y):
    return 10*x+y

b= np.fromfunction(f,(5,4),dtype=int)    #Construct an array by executing a function over each coordinate.
print("b= \n", b)

print("b[2,3]= \n", b[2,3])

print("b[0:5,1]= \n", b[0:5,1])
print("b[ : ,1]= \n", b[ : ,1])

print("b[1:3, : ]= \n", b[1:3, : ])

b= 
 [[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
b[2,3]= 
 23
b[0:5,1]= 
 [ 1 11 21 31 41]
b[ : ,1]= 
 [ 1 11 21 31 41]
b[1:3, : ]= 
 [[10 11 12 13]
 [20 21 22 23]]


### row , element , _.flat

In [1]:
import numpy as np
p= np.array([[0,1,2,3],
             [10,11,12,13],
             [20,21,22,23],
             [30,31,32,33],
             [40,41,42,43]])

for row in p:
    print(row)

for element in p.flat:
    print(element)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]
0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


### np.vstack() , np.hstack() , np.column_stack() , np.hsplit(array , indices_or_sections)

In [2]:
import numpy as np

aa=np.array([[1,2],
            [3,4]])
print("aa= \n",aa)

bb=np.array([[5,6],
            [7,8]])
print("bb= \n",bb)

print("vstack= \n", np.vstack((aa,bb)))
print("hstack= \n", np.hstack((aa,bb)))

aa= 
 [[1 2]
 [3 4]]
bb= 
 [[5 6]
 [7 8]]
vstack= 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
hstack= 
 [[1 2 5 6]
 [3 4 7 8]]


In [3]:
import numpy as np

in_array1= np.array([1,2,3])
print("input1= \n", in_array1)

in_array2= np.array([4,5,6])
print("input2= \n", in_array2)

out_array= np.column_stack([in_array1, in_array2])
print("output= \n", out_array)

input1= 
 [1 2 3]
input2= 
 [4 5 6]
output= 
 [[1 4]
 [2 5]
 [3 6]]


In [4]:
import numpy as np

in_array1= np.array([[1,2,3],[-1,-2,-3]])
print("input1= \n", in_array1)

in_array2= np.array([[4,5,6],[-4,-5,-6]])
print("input2= \n", in_array2)

out_array= np.column_stack([in_array1, in_array2])
print("output= \n", out_array)

input1= 
 [[ 1  2  3]
 [-1 -2 -3]]
input2= 
 [[ 4  5  6]
 [-4 -5 -6]]
output= 
 [[ 1  2  3  4  5  6]
 [-1 -2 -3 -4 -5 -6]]


In [5]:
import numpy as np

arr= np.array([[6.,7.,6.,9.,0.,5.,4.,0.,6.,8.,5.,2.,],
               [8.,5.,5.,7.,1.,8.,6.,7.,1.,8.,1.,0.,]])

x= np.hsplit(arr,3)    #hsplit splits an array into multiple sub-arrays horizontally (column-wise).
print("x= \n",x)

y=x.copy()
print("y= \n",y)

x= 
 [array([[6., 7., 6., 9.],
       [8., 5., 5., 7.]]), array([[0., 5., 4., 0.],
       [1., 8., 6., 7.]]), array([[6., 8., 5., 2.],
       [1., 8., 1., 0.]])]
y= 
 [array([[6., 7., 6., 9.],
       [8., 5., 5., 7.]]), array([[0., 5., 4., 0.],
       [1., 8., 6., 7.]]), array([[6., 8., 5., 2.],
       [1., 8., 1., 0.]])]


In [6]:
import numpy as np
x = np.arange(16.0).reshape(4, 4)
print("x= \n",x)
print("y= \n", np.hsplit(x, np.array([3, 6])))


x= 
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
y= 
 [array([[ 0.,  1.,  2.],
       [ 4.,  5.,  6.],
       [ 8.,  9., 10.],
       [12., 13., 14.]]), array([[ 3.],
       [ 7.],
       [11.],
       [15.]]), array([], shape=(4, 0), dtype=float64)]


### ma.concatenate(arrays , axis)

In [7]:
import numpy as np
import numpy.ma as ma

a1= np.array([1,2,3])
a2= np.array([4,5,6])

a= ma.concatenate([a1,a2])
print(a)

b= ma.concatenate([[a1],[a2]])
print(b)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


### len() 

In [8]:
import numpy as np

test_list= [[5,6,8],[7,4,3], [8,10,12]]

mult_list= [10,20,30]

print("test_list= ", test_list)
print("LenTestList= ", len(test_list))

print("mult_list= ", mult_list)

res= [[] for idx in range(len(test_list))]
for i in range(len(test_list)):
    for j in range(len(mult_list)):
        res[i]+= [mult_list[i]*test_list[i][j]]

print("the list after multiply: \n", res)

test_list=  [[5, 6, 8], [7, 4, 3], [8, 10, 12]]
LenTestList=  3
mult_list=  [10, 20, 30]
the list after multiply: 
 [[50, 60, 80], [140, 80, 60], [240, 300, 360]]


In [9]:
import numpy as np

a= np.arange(12).reshape(3,4)
print(a)
print("------------------")

i=np.array([[0,1],
            [1,2]])
print(a[i])
print("------------------")

j=np.array([[2,1],
            [3,3]])

print("index is: ", a[i,j])
print("-------------------")

print(a[i,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
------------------
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 4  5  6  7]
  [ 8  9 10 11]]]
------------------
index is:  [[ 2  5]
 [ 7 11]]
-------------------
[[ 2  6]
 [ 6 10]]


In [10]:
import numpy as np

a= np.array([0.0,10.0,20.0,30.0])
b= np.array([0.0,1.0,2.0])

print(a[:,np.newaxis]+b)

[[ 0.  1.  2.]
 [10. 11. 12.]
 [20. 21. 22.]
 [30. 31. 32.]]


### np.datetime64() , np.timedelta64(value , format) 

In [11]:
import numpy as np

today= np.datetime64('2020-02-12')
print("Date is:", today)
print("Year is:", np.datetime64(today, 'Y'))

dates= np.arange('2020-02', '2020-03', dtype= 'datetime64[D]')
print("\nDates of February, 2020: \n", dates)
print("Today is February:", today in dates)

dur= np.datetime64('2021-05-22') - np.datetime64('2020-05-22')
print("\nNo. of days:", dur)
print("No. of weeks:", np.timedelta64(dur, 'W'))

a=np.array(['2018-02-12','2019-10-13','2020-05-22'], dtype='datetime64')
print("\nDates in sorted order:", np.sort(a))

Date is: 2020-02-12
Year is: 2020

Dates of February, 2020: 
 ['2020-02-01' '2020-02-02' '2020-02-03' '2020-02-04' '2020-02-05'
 '2020-02-06' '2020-02-07' '2020-02-08' '2020-02-09' '2020-02-10'
 '2020-02-11' '2020-02-12' '2020-02-13' '2020-02-14' '2020-02-15'
 '2020-02-16' '2020-02-17' '2020-02-18' '2020-02-19' '2020-02-20'
 '2020-02-21' '2020-02-22' '2020-02-23' '2020-02-24' '2020-02-25'
 '2020-02-26' '2020-02-27' '2020-02-28' '2020-02-29']
Today is February: True

No. of days: 365 days
No. of weeks: 52 weeks

Dates in sorted order: ['2018-02-12' '2019-10-13' '2020-05-22']


### np.round_(value , decimals= ) 

In [12]:
import numpy as np

in_array= [.5,1.5,2.5,3.5,4.5,10.1]
print("Input array=\n", in_array)

round_of_values= np.round_(in_array)
print("\nRounded Values_\n", round_of_values)
print("---------------------------------------")
#############################################################
in_array= [.53,1.54,.71]
print("Input array=\n", in_array)

round_of_values= np.round_(in_array)
print("\nRounded Values_\n", round_of_values)
print("---------------------------------------")
############################################################
in_array= [.5538,1.33354,.71445]
print("Input array=\n", in_array)

round_of_values= np.round_(in_array, decimals=3)
print("\nRounded Values_\n", round_of_values)

Input array=
 [0.5, 1.5, 2.5, 3.5, 4.5, 10.1]

Rounded Values_
 [ 0.  2.  2.  4.  4. 10.]
---------------------------------------
Input array=
 [0.53, 1.54, 0.71]

Rounded Values_
 [1. 2. 1.]
---------------------------------------
Input array=
 [0.5538, 1.33354, 0.71445]

Rounded Values_
 [0.554 1.334 0.714]


## np.random.rand()  ,  np.random.randn()

In [14]:
import numpy as np  
a= np.random.rand(4,5)   #zwischen 0 und 1
print(a)

[[0.12649953 0.53098329 0.90069897 0.05977903 0.82084332]
 [0.33927203 0.64352441 0.47887149 0.87487417 0.70986953]
 [0.566284   0.0501875  0.66348492 0.43704511 0.02268241]
 [0.67545776 0.60882208 0.472861   0.35155508 0.10144342]]


In [13]:
import numpy as np
a= np.random.randn(4,5)     #random von normal Kurve
print(a)

[[-0.07296481  0.08299795 -0.49907675  0.2024926  -1.10114233]
 [-1.95564434  0.46398531 -0.29969118  1.89851807  1.53382248]
 [ 0.20869363 -0.47790584  0.22356269  0.05193199  0.40043329]
 [-0.37404723  0.50707912  1.0133104  -0.66783322 -0.65619231]]


## np.set_printoptions()

In [15]:
np.set_printoptions(formatter={'all': lambda x: '%.2f' % x})